### ISSUE TITLE
"Monkey Patching" mystery solved! -> suggest to revert changes

### ISSUE THREAD

**Issue by stsichler** [wolfgang-noichl/magick-rotation#4]
Hi,
regarding your note **_"Apparently, from 20.04 this somehow returns different stuff (possibly just recompile?)"_** about that line:
https://github.com/wolfgang-noichl/magick-rotation/blob/c89e6df9f2e7ef6342c482e11639b21a27d99616/listener.py#L68

Your assumption is wrong here, because the mystery was actually introduced by your commit 71667abb643f1ac3d953b769f9730fc84045d9fa when upgrading from Python 2.7 to Python 3.x, switching from `commands.getstatusoutput()` to `subprocess.getstatusoutput()` function:

- The `getstatusoutput()` function from `commands` Python module returns an exit status that ["_can be interpreted according to the rules for the C function wait()_"](https://docs.python.org/2.7/library/commands.html). From the according C-header file, this means `#define	__WEXITSTATUS(status)	(((status) & 0xff00) >> 8)`, explaining the division by 256 from the original code.
- The `getstatusoutput()` function from `subprocess` Python module instead returns an exit code that just ["_can be interpreted as the return code of subprocess_"](https://docs.python.org/3/library/subprocess.html). 

So from this point on, **the division by 256 breaks the code here**! This is the reason why you needed the "Monkey patching" which is now completely breaking the differentiation between different tablet state rotations.
So, I think it would be better to revert commit 27fe048379310d2a53296e2c80642a332df6eb49, at least in the _magick-rotation_ script, and instead remove that `/ 256` division.

**Comment by wolfgang-noichl** [comment]
Agreed, thanks. However, did you manage to get the GUI working by this?
On Xubuntu 22.04, I still get
```
  File "/home/wolfgang/magick-rotation-dev/./magick-rotation", line 165, in state_change
    self.tray.set_tooltip("Tablet mode")
AttributeError: 'tray_gui' object has no attribute 'set_tooltip'
```

so this doesn't entirely fix the GUI. I'd happily accept a PR that fixes that :)

**Comment by stsichler** [comment]
`set_tooltip` has been renamed to [`set_tooltip_text`](https://docs.gtk.org/gtk3/method.StatusIcon.set_tooltip_text.html) , that's all.
But it's also already deprecated since Gtk 3.14, but still working.

Please note that on my Linux Mint 21, _magick-rotation_ seems to be no longer necessary at all, because the tablet rotation seems to be managed somehow internally by the driver.
So, _magick-rotation_ even breaks the correct rotation, because it is rotating an already rotated device. 

Nevertheless, it may still be useful for starting some applications at mode switch.

**Comment by wolfgang-noichl** [comment]
> Please note that on my Linux Mint 21, magick-rotation seems to be no longer necessary at all, because the tablet rotation seems to be managed somehow internally by the driver.

That's with something that is not Xfce, right?

**Comment by stsichler** [comment]
Yes, I'm on Mint 21.3 Cinnamon Edition.

To be more precise, _magick-rotation_ seems still necessary to react to the hinge switch at all for switching between Normal and Tablet Mode, but it is no longer necessary to separately rotate the coordinates of Touch and Stylus input. This is obviously automatically adapted somewhere in the driver stack now.

**Comment by wolfgang-noichl** [comment]
I guess to fix this, one would need to put a check for Gnome3-alike in front of the rotation code. Feel free to make such a patch, I don't have any Gnome3/Cinnamon readily available.
